apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: podpresetbindingspecs.podpreset.svcat.k8s.io
spec:
  group: podpreset.svcat.k8s.io
  names:
    kind: PodPresetBindingSpec
    plural: podpresetbindingspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        bindingRef:
          type: object
        kind:
          type: string
        metadata:
          type: object
        podPresetTemplate:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                env:
                  items:
                    type: object
                  type: array
                envFrom:
                  items:
                    type: object
                  type: array
                selector:
                  type: object
                volumeMounts:
                  items:
                    type: object
                  type: array
                volumes:
                  items:
                    type: object
                  type: array
              required:
              - selector
              type: object
            status:
              type: object
          type: object
      required:
      - podPresetTemplate
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
